# Generated by Django 5.0.2 on 2024-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='course_image/default_book_image.png', upload_to='books_image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('davomiyligi', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'course_table',
            },
        ),
    ]
